name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EM_VERSION: 5.0.1
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v5
        with:
          path: |
            **/cpm_modules
            **/node_modules
            ${{env.EM_CACHE_FOLDER}}
          key: cpm-node-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '**/package-lock.json', env.EM_VERSION) }}-${{ runner.os }}
      - name: Setup emsdk with Emscripten
        uses: mymindstorm/setup-emsdk@v15
        with:
          version: ${{env.EM_VERSION}}
          emsdk-version: 5.0.5
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory, so make sure it doesn't conflict with anything!
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Verify Emscripten
        run: emcc -v
      - name: Install C++/CMake style checkers
        run: pip3 install clang-format==14.0.6 cmake_format==0.6.11 pyyaml
      - name: Install NPM packages
        env:
          CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
        run: npm install
      - name: Run NPM tests
        run: npm run test
      - name: check style
        run: npm run check:style
